apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rails
  labels:
    app: rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
        - image: busybox
          name: rails
          env:
            - name: RAILS_ENV
              value: "development"
            - name: DATABASE_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: DATABASE_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: database_root_password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: secret_key_base
            - name: DATABASE_PORT
              value: "3306"
          lifecycle:
            postStart:
              exec:
                command:
                - /bin/bash
                - -c
                - /app/post-start.sh
          ports:
            - containerPort: 3000
              name: rails
          command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
















